### ISSUE TITLE
NNTP Proxy

### ISSUE THREAD

**Issue by ghost** [greenbender/pynntp#2]
Hi,

I have been attempting to get NNTP Proxy to read the nZEDb/www/config.php file so that we can have the setting in a single location. I can get it to start but it fails when when in use.

I have added these to the standard settings. Could you help with this?

```
define('NNTP_PROXY_HOST', 'localhost');
define('NNTP_PROXY_PORT', 9991);
define('NNTP_PROXY_POOL', 30);
```

Thank you. The proxy seems to be working well.

**Comment by ldo** [comment]
That’s not Python code.

**Comment by greenbender** [comment]
This is an nZEDb issue
