### ISSUE TITLE
Request: Compatibility with Sabnzbd

### ISSUE THREAD

**Issue by Plecebo** [greenbender/pynntp#3]
It would be great if compatibility with sabnzbd could be looked into. I only have the one usenet subscription with a few apps that open connections. 

My current solution is to split my connections between pynntp and sabnzbd, but it seems logical that sabnzbd could just use pynnpt and pynntp could handle all connections to the news server.

**Comment by greenbender** [comment]
This is a very old issue, but for anyone else with this issue.

Creating an "NNTP reverse proxy" using this library is easily do-able. See https://github.com/nZEDb/nZEDb/blob/main/misc/update/python/nntpproxy.py for an example.
