### ISSUE TITLE
how to post?

### ISSUE THREAD

**Issue by wbui567** [greenbender/pynntp#6]
Hello,
I created a client connection. It's OK, but when I try to use the method post and I specify a file txt I want to post, it sends me back error.
I don't find any tutorial on stackoverflow to use pynntp to post on useneet.
Thanks with your help.

**Comment by cclauss** [comment]
What is the full error message?

**Comment by cclauss** [comment]
You need to post with headers and a body like:
https://github.com/greenbender/pynntp/blob/7bf2423fceafb80b4e1d82c593db1d3fd0297afb/tests/test_inn2.py#L84

**Comment by cclauss** [comment]
Is there still a TODO on this issue now?
