### ISSUE TITLE
I have another preservation project of nntplib

### ISSUE THREAD

**Issue by mcepl** [greenbender/pynntp#8]
I have removed `nntplib` module from PyPI in favour of your project, but I think you may find interesting things in what I have at https://git.sr.ht/~mcepl/nntplib

**Comment by Julien-Elie** [comment]
Oh, I understand now why `nntplib` was removed from PyPi...

I agree the interesting features of `nntplib` are worthwhile backporting.
In the README, I do not see the STAT and mere OVER and HDR commands.

**Comment by greenbender** [comment]
This repo is now in a much better place! Thanks to @cclauss jumping in over the weekend!. I plan to release verision 2.0.0 to pypi in the next week or so.

Please add issues or PRs if you would like to see features added. (I'll start with `STAT`, `OVER`, and `HDR`).

**Comment by Julien-Elie** [comment]
Thanks for your work @greenbender.  I have opened issues for a few suggestions of NNTP commands 😄

**Comment by cclauss** [comment]
Is there still a TODO on this issue now that Python 3.13 has been released?
* https://www.python.org/downloads/release/python-3130/
* https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-remove-dead-batteries-from-the-standard-library
